# Keys
title = "My TOML Config"

# Tables
[sms]
origin = "ICUBAM"
carrier = "nx"

[db]
sqlite_path = "icubam.db"

[server]
  [server.dev]
  PORT = 8888  # will be lower cased when reading.
  base_url = "https://localhost:8888/"
  [server.prod]
  port = 443
  base_url = "https://test.icubam.net/"

[scheduler]
  [scheduler.prod]
  max_retries = 3
  [scheduler.dev]
  max_retries = 1
