name: Python package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # https://github.com/marketplace/actions/setup-miniconda
    - uses: actions/checkout@v2
    - uses: goanpeca/setup-miniconda@v1
      with:
         activate-environment: anaconda-client-env
         python-version: 3.8
         auto-activate-base: false
    - shell: bash -l {0}
      run: |
        conda info
        conda list
        python --version
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        sudo apt-get update
        sudo apt-get install sqlite3
        sqlite3 -version
    - name: Test with pytest
      run: |
        pip install pytest
        pytest .
