name: Python package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # https://github.com/marketplace/actions/setup-miniconda
    - uses: goanpeca/setup-miniconda@v1
      with:
        auto-update-conda: true
        python-version: '3.8'
    - name: Info
      run: |
        conda info
        python --version
    - name: Cache pip
      uses: actions/cache@v1
      with:
        # Cache pip accordingly to https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#caching-dependencies
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          ${{ runner.os }}-
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        sudo apt-get update
        sudo apt-get install sqlite3
        sqlite3 -version
    - name: Test with pytest
      run: |
        pip install pytest
        pytest .
