name: Python package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # https://github.com/marketplace/actions/setup-miniconda
    - uses: actions/checkout@v2
    - uses: goanpeca/setup-miniconda@v1
      with:
         activate-environment: anaconda-client-env
         python-version: 3.8
         auto-activate-base: false
    - shell: bash -l {0}
      run: |
        conda info
        python --version
    - name: Install dependencies
    - shell: bash -l {0}
      run: |
        which python
        pip install -r requirements.txt
    - name: Test with pytest
    - shell: bash -l {0}
      run: |
        pip install pytest
        pytest .
